### ISSUE TITLE
wp-cli

### ISSUE THREAD

**Issue by danielforsberg** [Darep/wordpress-boilerplate#2]
Is there a way to get [wp-cli] (http://wp-cli.org/) to work with this?

**Comment by Darep** [comment]
Not sure, I haven't used [wp-cli](http://wp-cli.org/), and unfortunately don't have the time to check it :(

**Comment by basteln3rk** [comment]
I just tried it with wp-cli 0.21.1 and it works out of the box if you launch it from the ``wordpress`` subdirectory. 

## Example: Using wp-cli with wordpress-boilerplate

```
wordpress-boilerplate$ wp core version
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
wordpress-boilerplate$ cd wordpress
wordpress$ wp core version
4.4
```

**Comment by Darep** [comment]
Cool, thanks @basteln3rk for checking it out! :) Does the `wp` find the plugin and theme paths correctly? So that it doesn't save plugins or themes under the `wordpress/` directory? I will have a quick look at it myself as well :)

**Comment by Darep** [comment]
I added a `wp-cli.yml` file to the root so now you should be able to use wp-cli's wp command in the root directory :) Seemed to work, tested installing a few plugins and themes with it. But some of the core commands e.g. `wp core install` seem to break the git subtree thing so I suggest being aware of what wp-cli is doing when running commands :)

**Comment by basteln3rk** [comment]
@Darep thanks or adding the config! For me, the theme and plugin installation/update seem to work very well and are a really good fit with the approach of the wordpress boilerplate.

**Comment by Darep** [comment]
You're welcome! :) Hopefully it's good now. I'll close this issue, if there's any problems, feel free to comment & re-open!
